// Public path is specfied in HTML and maybe dynamicly generated by server for different request.
// See `window.publicPath` in ../public/index.html
__webpack_public_path__ = window["publicPath"];

require("./index.tsx");

export {}; // Fix the error "All files must be modules when the '--isolatedModules' flag is provided".
