name: CI

on:
- push
- pull_request

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Set up Node
      uses: actions/setup-node@v2-beta
      with:
        node-version: 14.x
    - name: Install
      run: yarn
    - name: Build
      run: SYZOJ_NG_APP_CONFIG_FILE=./config-example.yaml yarn build
    - name: Check style
      run: yarn format --check
